name: Test cache

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [assigned, opened, synchronize, reopened]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - cc: clang-14
            cxx: clang++-14
            mode: Debug
          - cc: gcc-11
            cxx: g++-11
            mode: Release

    steps:
      - name: Try restoring LLVM cache
        id: restore-llvm-cache
        uses: actions/cache/restore@v3
        with:
          path: |
            tpls/llvm/build/bin/llvm-lit
            tpls/llvm/llvm/utils/lit
            tpls/llvm/install
          key: Linux-llvm-c0b45fef155fbe3f17f9a6f99074682c69545488-c6445c01f9f4f9c8585fa277d73df655-clang-14


